### ISSUE TITLE
ESP32 error: 'TwoWire' does not name a type; did you mean 'TwoWire_h'

### ISSUE THREAD

**Issue by spplecxer** [pololu/vl53l1x-arduino#25]
Trying to use this in esphome and getting this error on compile:

src/esphome/components/i2c/i2c_bus_arduino.h:36:3: error: 'TwoWire' does not name a type; did you mean 'TwoWire_h'?

using this code:

https://github.com/jardous/tof_vl53l1x

**Comment by kevin-pololu** [comment]
The error you're getting does not seem directly related to this library, and we're not familiar with ESPHome, so I suggest trying to get help from the ESPHome community. If you're able to determine more conclusively that the error is caused by a problem with our library, feel free to reopen this issue.
