### ISSUE TITLE
Failed to detect sensor

### ISSUE THREAD

**Issue by Gbouna** [pololu/vl53l1x-arduino#7]
Thank you for this example it is really helpful. However, when i uploaded the code to Arduino Mega, then opened my serial monitor, it shows "Failed to detect and initialize sensor!". What could be the possible problem why the sensor failed to be detected and initialized. 
Thank you

**Comment by kevin-pololu** [comment]
That typically means the Arduino is unable to communicate with the sensor (for example, because of bad connections). If you are still having trouble with this, please post to [the Pololu forum](https://forum.pololu.com/), since that is a more appropriate place for troubleshooting. It would be helpful if you include pictures of your setup so we can check your wiring and soldering.

**Comment by Gbouna** [comment]
okay thank you, i will do just that
